Added Underline on Hover
omnidevZero/YouTubeRedux pull request #87
Opened 2022-11-08 21:08 UTC by lewisgilldotcom

This feature was present on all YouTube versions from 2008-2019

2022-11-14 12:08 UTC, omnidevZero requested changes

2022-11-24 13:03 UTC, lewisgilldotcom commented on Chrome/styles.css
> +    font-size: min(14px, calc((90 / var(--ytd-rich-grid-items-per-row)) * 1px)) !important;
Okay all issues should be addressed now. This is my first pull request so this is all very new to me, please accept my apologies if I've missed something obvious. :)

2022-11-25 15:01 UTC, omnidevZero commented on Chrome/styles.css
> +    font-size: min(14px, calc((90 / var(--ytd-rich-grid-items-per-row)) * 1px)) !important;
Looks good! Thanks for the contribution!

2022-11-25 15:02 UTC, omnidevZero approved these changes

2022-11-25 15:02 UTC, merged